version: "3"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    networks:
        - sharednet

  frontend:
    build: 
        context: frontend
        dockerfile: Dockerfile
    container_name: frontend
    ports:
        - "80:80"
    networks:
        - sharednet

networks:
    sharednet:
        driver: bridge